# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.qmd']

name: render-quarto.yaml

permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto files and Commit Results
        run: |
          QMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]qmd$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) quarto::render(f)' ${QMD_PATH[*]}
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit ${QMD_PATH[*]/.qmd/.md} -m 'Re-build Quatro files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
