# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Example from: https://github.com/posit-conf-2025/r-production/blob/main/1-render-qmd.yaml
on:
  push:
#    paths: ['**.qmd']
    branches: main

name: render-quarto.yaml

permissions: read-all

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Install quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # Render the quarto file into html/
      - name: Render
        run: quarto render index.qmd --output-dir=html

      # Publish html/ to GitHub pages
      - name: Publish to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: html
